Filtros timeline
M-Borba/PIS-FrontEnd pull request #55
Opened 2021-11-04 21:02 UTC by M-Borba

- Se arregla detalle de estilo en tamaños de texto al ver info de projecto en timeline
- Se envian los filtros seleccionados en ambas timeline al backend

2021-11-04 22:04 UTC, juanbazpera commented on src/components/FilterForm/index.js
> +        >
- autofocus debe estar en solo un input, sino el navegador se marea y no sabe a cual hacer foco
- labelId no seria necesario no?
- el margin creo que podriamos sacarle el normal
- Tener `<TextField select />` en vez de` <Select... />` te ahorra de poner form control y label? Pregunta para saber nomas

2021-11-04 22:04 UTC, juanbazpera commented on src/components/FilterForm/index.js
> +        />
👀

2021-11-04 22:04 UTC, juanbazpera commented on src/components/FilterForm/index.js
> +      </form>
este box es necesario?

2021-11-04 22:05 UTC, juanbazpera commented on src/components/FilterForm/styles.js
> +  },
esto no se usa no?

2021-11-04 22:05 UTC, juanbazpera commented on src/components/FilterForm/styles.js
> +  },
gap es de grid, creo que no iria aca

2021-11-04 22:06 UTC, juanbazpera commented on src/components/FilterForm/styles.js
> +  },
esto funciona? creo que debe ser 1, 2 o 4 argumentos

2021-11-04 22:07 UTC, juanbazpera commented on src/containers/InfoProyecto/index.js
>            {projectData.description}
deberia ir display="" aca?

2021-11-04 22:09 UTC, juanbazpera commented on src/containers/PersonView/CustomTimeline.js
> +  };
```suggestion
  const onFilterChange = (e) => {
    setFilters(prev => ({...prev, [e.target.name]: e.target.value}))
  };
```

2021-11-04 22:09 UTC, juanbazpera commented on src/components/FilterForm/index.js
> +          type="text"
deberiamos agregar `name="project_type"`, hago referencia mas abajo sobre eso

2021-11-04 22:11 UTC, juanbazpera commented on src/containers/PersonView/CustomTimeline.js
```suggestion
        rows.map((ppl) => {
           const person = ppl.person;

```

2021-11-04 22:11 UTC, juanbazpera commented on src/containers/PersonView/CustomTimeline.js
> +              startDate.setDate(startDate.getDate());
```suggestion
            proj.dates.map((dt) => {
              const startDate = new Date(dt.start_date);
              startDate.setDate(startDate.getDate());
```

2021-11-04 22:14 UTC, juanbazpera commented on src/containers/PersonView/CustomTimeline.js
> +              endDate.setDate(endDate.getDate() + 1);
porque sumamos 1 aca? y si end_date es nulo?

2021-11-04 22:16 UTC, juanbazpera commented on src/containers/PersonView/CustomTimeline.js
> +                endDate = new Date(2050, 1, 1);
`moment().add(5, 'years');` porque si la app dura hasta el 2050 se rompe toda 😅

2021-11-04 22:16 UTC, juanbazpera commented on src/containers/PersonView/CustomTimeline.js
> +              });
```suggestion
                canMove: false,
                title: `${proj.name}  ${rolesFormateados[dt.role]}`,
              });
```

2021-11-04 22:17 UTC, juanbazpera commented on src/containers/PersonView/CustomTimeline.js
> +                canResize: "both",
agregar 3 horas, creo que se podria formatear con moment mas arriba, sino es como que en cada linea le agregamos un puchito de codigo a los dates

2021-11-04 22:17 UTC, juanbazpera commented on src/containers/ProjectView/CustomTimeline.js
> +
Lo mismo que arriba

2021-11-04 22:18 UTC, juanbazpera requested changes
Solo unos cambios

2021-11-05 13:21 UTC, M-Borba commented on src/components/FilterForm/styles.js
> +  },
Para flexbox anda también anda, es para que no queden pegados

2021-11-05 15:10 UTC, M-Borba commented on src/components/FilterForm/index.js
> +        >
En realidad si usaba Select se veía raro(más chico que el resto de los campos), la recomendación que encontré fue usar TextField

2021-11-05 15:20 UTC, M-Borba commented on src/components/FilterForm/styles.js
> +  },
Anda, son opcionales los argumentos, pero ahora q lo mencionas no es necesario ese margen

2021-11-08 00:36 UTC, merged